Type.registerNamespace('Roblox.Website.Services.Secure');Roblox.Website.Services.Secure.AddParentEmail=function(){Roblox.Website.Services.Secure.AddParentEmail.initializeBase(this);this._timeout=0;this._userContext=null;this._succeeded=null;this._failed=null;}
Roblox.Website.Services.Secure.AddParentEmail.prototype={_get_path:function(){var p=this.get_path();if(p)return p;else return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_path();},InsertParentEmail:function(emailAddress,userID,pwd,ClientIpAddress,resetParentEmail,succeededCallback,failedCallback,userContext){return this._invoke(this._get_path(),'InsertParentEmail',false,{emailAddress:emailAddress,userID:userID,pwd:pwd,ClientIpAddress:ClientIpAddress,resetParentEmail:resetParentEmail},succeededCallback,failedCallback,userContext);}}
Roblox.Website.Services.Secure.AddParentEmail.registerClass('Roblox.Website.Services.Secure.AddParentEmail',Sys.Net.WebServiceProxy);Roblox.Website.Services.Secure.AddParentEmail._staticInstance=new Roblox.Website.Services.Secure.AddParentEmail();Roblox.Website.Services.Secure.AddParentEmail.set_path=function(value){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.set_path(value);}
Roblox.Website.Services.Secure.AddParentEmail.get_path=function(){return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_path();}
Roblox.Website.Services.Secure.AddParentEmail.set_timeout=function(value){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.set_timeout(value);}
Roblox.Website.Services.Secure.AddParentEmail.get_timeout=function(){return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_timeout();}
Roblox.Website.Services.Secure.AddParentEmail.set_defaultUserContext=function(value){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.set_defaultUserContext(value);}
Roblox.Website.Services.Secure.AddParentEmail.get_defaultUserContext=function(){return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_defaultUserContext();}
Roblox.Website.Services.Secure.AddParentEmail.set_defaultSucceededCallback=function(value){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.set_defaultSucceededCallback(value);}
Roblox.Website.Services.Secure.AddParentEmail.get_defaultSucceededCallback=function(){return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_defaultSucceededCallback();}
Roblox.Website.Services.Secure.AddParentEmail.set_defaultFailedCallback=function(value){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.set_defaultFailedCallback(value);}
Roblox.Website.Services.Secure.AddParentEmail.get_defaultFailedCallback=function(){return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_defaultFailedCallback();}
Roblox.Website.Services.Secure.AddParentEmail.set_enableJsonp=function(value){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.set_enableJsonp(value);}
Roblox.Website.Services.Secure.AddParentEmail.get_enableJsonp=function(){return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_enableJsonp();}
Roblox.Website.Services.Secure.AddParentEmail.set_jsonpCallbackParameter=function(value){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.set_jsonpCallbackParameter(value);}
Roblox.Website.Services.Secure.AddParentEmail.get_jsonpCallbackParameter=function(){return Roblox.Website.Services.Secure.AddParentEmail._staticInstance.get_jsonpCallbackParameter();}
Roblox.Website.Services.Secure.AddParentEmail.set_path("/Services/Secure/AddParentEmail.asmx");Roblox.Website.Services.Secure.AddParentEmail.InsertParentEmail=function(emailAddress,userID,pwd,ClientIpAddress,resetParentEmail,onSuccess,onFailed,userContext){Roblox.Website.Services.Secure.AddParentEmail._staticInstance.InsertParentEmail(emailAddress,userID,pwd,ClientIpAddress,resetParentEmail,onSuccess,onFailed,userContext);}